services:
  sneezy-db:
    image: ghcr.io/sneezymud/sneezy-db:latest

  sneezy:
    image: ghcr.io/sneezymud/sneezymud:latest
    volumes:
      - sneezy-mutable:/home/sneezy/lib/mutable
      - type: bind
        source: ./discord.cfg
        target: /home/sneezy/code/discord.cfg
        bind:
          create_host_path: false
    restart: "no"
    environment:
      - ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:handle_segv=0:handle_sigbus=0:handle_sigfpe=0:handle_sigill=0:abort_on_error=1
      - UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=0

  buildertools:
    image: ghcr.io/sneezymud/sneezymud-buildertools:latest

  webclient:
    image: ghcr.io/sneezymud/webclient:latest

  sneezy-monitor:
    container_name: sneezy-monitor
    image: ghcr.io/sneezymud/sneezy-monitor:latest
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
      - /var/tmp/sneezymud-logs:/logs
    environment:
      - CONTAINER_NAME=sneezy
      - IMAGE_NAME=ghcr.io/sneezymud/sneezymud:latest
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
    restart: always
    depends_on:
      sneezy-db:
        condition: service_healthy
