services:
  sneezy-db:
    image: sneezymud/sneezy-db:57

  sneezy:
    image: sneezymud/sneezymud:latest
    volumes:
      - sneezy-mutable:/home/sneezy/lib/mutable
      - type: bind
        source: ./discord.cfg
        target: /home/sneezy/code/discord.cfg
        bind:
          create_host_path: false
    restart: "no"
    environment:
      - ASAN_OPTIONS=handle_segv=0:handle_sigbus=0:handle_sigfpe=0:handle_sigill=0:abort_on_error=1

  buildertools:
    image: sneezymud/sneezymud-buildertools:59

  webclient:
    image: sneezymud/webclient:60

  sneezy-monitor:
    container_name: sneezy-monitor
    build:
      context: services/monitor
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
      - /var/tmp/sneezymud-logs:/logs
    environment:
      - CONTAINER_NAME=sneezy
      - IMAGE_NAME=sneezymud/sneezymud:latest
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
    restart: always
    depends_on:
      - sneezy-db
