// Discipline file IDs (0-71 with gaps) from mapDiscToFile() in enum.cc.
// Used by APPLY_DISCIPLINE (file value 38) mod1 field.

import type { EnumEntry } from "../types/enums.ts";

export const DISCIPLINE_TYPES: EnumEntry[] = [
  { label: "Mage", value: 0 },
  { label: "Air", value: 1 },
  { label: "Alchemy", value: 2 },
  { label: "Earth", value: 3 },
  { label: "Fire", value: 4 },
  { label: "Sorcery", value: 5 },
  { label: "Spirit", value: 6 },
  { label: "Water", value: 7 },
  { label: "Cleric", value: 8 },
  { label: "Wrath", value: 9 },
  { label: "Afflictions", value: 10 },
  { label: "Aegis", value: 11 },
  { label: "Cures", value: 12 },
  { label: "Hand of God", value: 13 },
  { label: "Warrior", value: 14 },
  { label: "Dueling", value: 15 },
  { label: "Brawling", value: 16 },
  { label: "Soldiering", value: 17 },
  { label: "Blacksmithing", value: 18 },
  { label: "Ranger", value: 19 },
  { label: "Bogus 1", value: 20 },
  { label: "Shaman Armadillo", value: 21 },
  { label: "Animal", value: 22 },
  { label: "Plants", value: 23 },
  { label: "Bogus 2", value: 24 },
  { label: "Deikhan", value: 25 },
  { label: "Deikhan Martial", value: 26 },
  { label: "Mounted", value: 27 },
  { label: "Deikhan Guardian", value: 28 },
  { label: "Deikhan Absolution", value: 29 },
  { label: "Deikhan Vengeance", value: 30 },
  { label: "Monk", value: 31 },
  { label: "Meditation", value: 32 },
  { label: "Leverage", value: 33 },
  { label: "Mind & Body", value: 34 },
  { label: "Focused Attacks", value: 37 },
  { label: "Barehand", value: 39 },
  { label: "Thief", value: 40 },
  { label: "Thief Fight", value: 41 },
  { label: "Murder", value: 42 },
  { label: "Looting", value: 43 },
  { label: "Poisons", value: 44 },
  { label: "Stealth", value: 45 },
  { label: "Traps", value: 46 },
  { label: "Shaman", value: 47 },
  { label: "Shaman Frog", value: 48 },
  { label: "Shaman Alchemy", value: 49 },
  { label: "Shaman Skunk", value: 50 },
  { label: "Shaman Spider", value: 51 },
  { label: "Shaman Control", value: 52 },
  { label: "Ritualism", value: 53 },
  { label: "Wizardry", value: 54 },
  { label: "Faith", value: 55 },
  { label: "Slash", value: 56 },
  { label: "Blunt", value: 57 },
  { label: "Pierce", value: 58 },
  { label: "Ranged", value: 59 },
  { label: "Combat", value: 60 },
  { label: "Adventuring", value: 61 },
  { label: "Theology", value: 62 },
  { label: "Lore", value: 63 },
  { label: "Nature", value: 64 },
  { label: "Defense", value: 65 },
  { label: "Psionics", value: 66 },
  { label: "Shaman Healing", value: 67 },
  { label: "Iron Body", value: 68 },
  { label: "Advanced Adventuring", value: 69 },
  { label: "Commoner", value: 70 },
  { label: "Offense", value: 71 },
];
