import type { BitfieldEntry } from "./types.ts";

export const EXTRA_FLAGS: BitfieldEntry[] = [
  { bit: 0, label: "Glow" },
  { bit: 1, label: "Hum" },
  { bit: 2, label: "Strung" },
  { bit: 3, label: "Shadowy" },
  { bit: 4, label: "Prototype" },
  { bit: 5, label: "Invisible" },
  { bit: 6, label: "Magic" },
  { bit: 7, label: "Nodrop" },
  { bit: 8, label: "Bless" },
  { bit: 9, label: "Spiked" },
  { bit: 10, label: "Hover" },
  { bit: 11, label: "Rusty" },
  { bit: 12, label: "Anti-Cleric" },
  { bit: 13, label: "Anti-Mage" },
  { bit: 14, label: "Anti-Thief" },
  { bit: 15, label: "Anti-Warrior" },
  { bit: 16, label: "Anti-Shaman" },
  { bit: 17, label: "Anti-Deikhan" },
  { bit: 18, label: "Anti-Ranger" },
  { bit: 19, label: "Anti-Monk" },
  { bit: 20, label: "Paired" },
  { bit: 21, label: "Norent" },
  { bit: 22, label: "Float" },
  { bit: 23, label: "Nopurge" },
  { bit: 24, label: "Newbie" },
  { bit: 25, label: "Nojunk Player" },
  { bit: 26, label: "Silvered" },
  { bit: 28, label: "Attached" },
  { bit: 29, label: "Burning" },
  { bit: 30, label: "Charred" },
  { bit: 31, label: "Nolocate" },
];
