import type { EnumEntry } from "./types.ts";

export const IMMUNITY_TYPES: EnumEntry[] = [
  { label: "Heat", value: 0 },
  { label: "Cold", value: 1 },
  { label: "Acid", value: 2 },
  { label: "Poison", value: 3 },
  { label: "Sleep", value: 4 },
  { label: "Paralysis", value: 5 },
  { label: "Charm", value: 6 },
  { label: "Pierce", value: 7 },
  { label: "Slash", value: 8 },
  { label: "Blunt", value: 9 },
  { label: "Non-Magic", value: 10 },
  { label: "+1 Weapons", value: 11 },
  { label: "+2 Weapons", value: 12 },
  { label: "+3 Weapons", value: 13 },
  { label: "Air", value: 14 },
  { label: "Energy", value: 15 },
  { label: "Electricity", value: 16 },
  { label: "Disease", value: 17 },
  { label: "Suffocation", value: 18 },
  { label: "Skin Condition", value: 19 },
  { label: "Bone Condition", value: 20 },
  { label: "Bleed", value: 21 },
  { label: "Water", value: 22 },
  { label: "Drain", value: 23 },
  { label: "Fear", value: 24 },
  { label: "Earth", value: 25 },
  { label: "Summon", value: 26 },
  { label: "Holy", value: 27 },
];
