import type { EnumEntry } from "./types.ts";

export const ITEM_TYPES: EnumEntry[] = [
  { label: "Undefined", value: 0 },
  { label: "Light", value: 1 },
  { label: "Scroll", value: 2 },
  { label: "Wand", value: 3 },
  { label: "Staff", value: 4 },
  { label: "Weapon", value: 5 },
  { label: "Fuel", value: 6 },
  { label: "Opal", value: 7 },
  { label: "Treasure", value: 8 },
  { label: "Armor", value: 9 },
  { label: "Potion", value: 10 },
  { label: "Worn", value: 11 },
  { label: "Other", value: 12 },
  { label: "Trash", value: 13 },
  { label: "Trap", value: 14 },
  { label: "Chest/Container", value: 15 },
  { label: "Note", value: 16 },
  { label: "Drink Container", value: 17 },
  { label: "Key", value: 18 },
  { label: "Food", value: 19 },
  { label: "Money", value: 20 },
  { label: "Pen", value: 21 },
  { label: "Boat", value: 22 },
  { label: "Audio", value: 23 },
  { label: "Board", value: 24 },
  { label: "Bow", value: 25 },
  { label: "Arrow", value: 26 },
  { label: "Bag", value: 27 },
  { label: "Corpse", value: 28 },
  { label: "Spell Bag", value: 29 },
  { label: "Component", value: 30 },
  { label: "Book", value: 31 },
  { label: "Portal", value: 32 },
  { label: "Window", value: 33 },
  { label: "Tree", value: 34 },
  { label: "Tool", value: 35 },
  { label: "Holy Symbol", value: 36 },
  { label: "Quiver", value: 37 },
  { label: "Bandage", value: 38 },
  { label: "Statue", value: 39 },
  { label: "Bed", value: 40 },
  { label: "Table", value: 41 },
  { label: "Raw Material", value: 42 },
  { label: "Gemstone", value: 43 },
  { label: "Martial Weapon", value: 44 },
  { label: "Jewelry", value: 45 },
  { label: "Vial", value: 46 },
  { label: "Player Corpse", value: 47 },
  { label: "Pool", value: 48 },
  { label: "Keyring", value: 49 },
  { label: "Raw Organic", value: 50 },
  { label: "Flame", value: 51 },
  { label: "Applied Substance", value: 52 },
  { label: "Gas", value: 53 },
  { label: "Armor Wand", value: 54 },
  { label: "Drug Container", value: 55 },
  { label: "Drug", value: 56 },
  { label: "Gun", value: 57 },
  { label: "Ammo", value: 58 },
  { label: "Plant", value: 59 },
  { label: "Cookware", value: 60 },
  { label: "Vehicle", value: 61 },
  { label: "Casino Chip", value: 62 },
  { label: "Poison", value: 63 },
  { label: "Handgonne", value: 64 },
  { label: "Egg", value: 65 },
  { label: "Cannon", value: 66 },
  { label: "Tooth Necklace", value: 67 },
  { label: "Trash Pile", value: 68 },
  { label: "Card Deck", value: 69 },
  { label: "Suitcase", value: 70 },
  { label: "Saddle", value: 71 },
  { label: "Harness", value: 72 },
  { label: "Saddlebag", value: 73 },
  { label: "Wagon", value: 74 },
  { label: "Money Pouch", value: 75 },
  { label: "Fruit", value: 76 },
];
