import type { EnumEntry } from "../types/enums.ts";

export const MATERIAL_TYPES: EnumEntry[] = [
  // General
  { label: "Undefined", value: 0 },
  { label: "Paper", value: 1 },
  { label: "Cloth", value: 2 },
  { label: "Wax", value: 3 },
  { label: "Glass", value: 4 },
  { label: "Wood", value: 5 },
  { label: "Silk", value: 6 },
  { label: "Foodstuff", value: 7 },
  { label: "Plastic", value: 8 },
  { label: "Rubber", value: 9 },
  { label: "Cardboard", value: 10 },
  { label: "String", value: 11 },
  { label: "Plasma", value: 12 },
  { label: "Tough Cloth", value: 13 },
  { label: "Coral", value: 14 },
  { label: "Horsehair", value: 15 },
  { label: "Hair", value: 16 },
  { label: "Powder", value: 17 },
  { label: "Pumice", value: 18 },
  { label: "Laminated", value: 19 },
  // Nature
  { label: "Generic Organic", value: 50 },
  { label: "Leather", value: 51 },
  { label: "Tough Leather", value: 52 },
  { label: "Dragon Scale", value: 53 },
  { label: "Wool", value: 54 },
  { label: "Fur", value: 55 },
  { label: "Feathered", value: 56 },
  { label: "Water", value: 57 },
  { label: "Fire", value: 58 },
  { label: "Earth", value: 59 },
  { label: "Elemental", value: 60 },
  { label: "Ice", value: 61 },
  { label: "Lightning", value: 62 },
  { label: "Chaos", value: 63 },
  { label: "Clay", value: 64 },
  { label: "Porcelain", value: 65 },
  { label: "Straw", value: 66 },
  { label: "Pearl", value: 67 },
  { label: "Human Flesh", value: 68 },
  { label: "Fur (Cat)", value: 69 },
  { label: "Fur (Dog)", value: 70 },
  { label: "Fur (Rabbit)", value: 71 },
  { label: "Ghostly", value: 72 },
  { label: "Dwarf Leather", value: 73 },
  { label: "Soft Leather", value: 74 },
  { label: "Fishscale", value: 75 },
  { label: "Ogre Hide", value: 76 },
  { label: "Hemp", value: 77 },
  // Mineral
  { label: "Generic Mineral", value: 100 },
  { label: "Runestone", value: 102 },
  { label: "Crystal", value: 103 },
  { label: "Diamond", value: 104 },
  { label: "Ebony", value: 105 },
  { label: "Emerald", value: 106 },
  { label: "Ivory", value: 107 },
  { label: "Obsidian", value: 108 },
  { label: "Onyx", value: 109 },
  { label: "Opal", value: 110 },
  { label: "Ruby", value: 111 },
  { label: "Sapphire", value: 112 },
  { label: "Marble", value: 113 },
  { label: "Stone", value: 114 },
  { label: "Bone", value: 115 },
  { label: "Jade", value: 116 },
  { label: "Amber", value: 117 },
  { label: "Turquoise", value: 118 },
  { label: "Amethyst", value: 119 },
  { label: "Mica", value: 120 },
  { label: "Dragonbone", value: 121 },
  { label: "Malachite", value: 122 },
  { label: "Granite", value: 123 },
  { label: "Quartz", value: 124 },
  { label: "Jet", value: 125 },
  { label: "Corundum", value: 126 },
  // Metal
  { label: "Copper", value: 151 },
  { label: "Bronze", value: 156 },
  { label: "Brass", value: 157 },
  { label: "Iron", value: 158 },
  { label: "Steel", value: 159 },
  { label: "Mithril", value: 160 },
  { label: "Adamantite", value: 161 },
  { label: "Silver", value: 162 },
  { label: "Gold", value: 163 },
  { label: "Platinum", value: 164 },
  { label: "Titanium", value: 165 },
  { label: "Aluminum", value: 166 },
  { label: "Nickel", value: 168 },
  { label: "Electrum", value: 169 },
  { label: "Athanor", value: 170 },
  { label: "Tin", value: 171 },
  { label: "Tungsten", value: 172 },
  { label: "Starmetal", value: 173 },
  { label: "Terbium", value: 174 },
  { label: "Eternium", value: 177 },
];
