import type { EnumEntry } from "../types/enums.ts";

export const MOB_SPEC_PROCS: EnumEntry[] = [
  { label: "None", value: 0 },
  { label: "energy drainer", value: 1 },
  { label: "arch vampire", value: 2 },
  { label: "dragon breath", value: 3 },
  { label: "thief", value: 4 },
  { label: "janitor", value: 5 },
  { label: "tormentor", value: 6 },
  { label: "Trainer: air", value: 7 },
  { label: "chicken", value: 8 },
  { label: "thrower mob", value: 9 },
  { label: "swallower", value: 10 },
  { label: "bounty hunter", value: 11 },
  { label: "alignment god", value: 12 },
  { label: "engraver", value: 13 },
  { label: "cityguard", value: 14 },
  { label: "dagger thrower", value: 15 },
  { label: "mount", value: 16 },
  { label: "beggar", value: 17 },
  { label: "pet keeper", value: 18 },
  { label: "stable man", value: 19 },
  { label: "famine", value: 20 },
  { label: "war", value: 21 },
  { label: "cold giver", value: 22 },
  { label: "flu giver", value: 23 },
  { label: "craps man", value: 24 },
  { label: "shop keeper", value: 25 },
  { label: "postmaster", value: 26 },
  { label: "receptionist", value: 27 },
  { label: "rock worm", value: 28 },
  { label: "mage guildmaster", value: 29 },
  { label: "deikhan guildmaster", value: 30 },
  { label: "monk guildmaster", value: 31 },
  { label: "warrior guildmaster", value: 32 },
  { label: "thief guildmaster", value: 33 },
  { label: "cleric guildmaster", value: 34 },
  { label: "ranger guildmaster", value: 35 },
  { label: "hobbit emissary", value: 36 },
  { label: "Trainer: alchemy", value: 37 },
  { label: "Trainer: earth", value: 38 },
  { label: "repairman", value: 39 },
  { label: "sharpener", value: 40 },
  { label: "rust monster", value: 41 },
  { label: "paralyze bite", value: 42 },
  { label: "caravan leader", value: 43 },
  { label: "death", value: 44 },
  { label: "pestilence", value: 45 },
  { label: "firemaster", value: 46 },
  { label: "paralyze breath", value: 47 },
  { label: "doctor", value: 48 },
  { label: "Trainer: fire", value: 49 },
  { label: "frostbiter", value: 50 },
  { label: "ticket-guy", value: 51 },
  { label: "fireballer", value: 52 },
  { label: "teleporter", value: 53 },
  { label: "meteorswarm", value: 54 },
  { label: "icestormer", value: 55 },
  { label: "energy drainer2", value: 56 },
  { label: "lightning bolter", value: 57 },
  { label: "disintigrater", value: 58 },
  { label: "witherer", value: 59 },
  { label: "paralyzer2", value: 60 },
  { label: "acid blaster", value: 61 },
  { label: "king Urik", value: 62 },
  { label: "Trainer: sorcery", value: 63 },
  { label: "Trainer: spirit", value: 64 },
  { label: "Trainer: water", value: 65 },
  { label: "Trainer: wrath", value: 66 },
  { label: "Trainer: afflictions", value: 67 },
  { label: "Trainer: cures", value: 68 },
  { label: "Trainer: hand of god", value: 69 },
  { label: "Trainer: ranger", value: 70 },
  { label: "replicant", value: 71 },
  { label: "Trainer: looting", value: 72 },
  { label: "Trainer: murder", value: 73 },
  { label: "Trainer: hand-to-hand", value: 74 },
  { label: "Trainer: adventuring", value: 75 },
  { label: "Trainer: warrior", value: 76 },
  { label: "Banshee", value: 77 },
  { label: "Meeting Organizer", value: 78 },
  { label: "toll taker", value: 79 },
  { label: "Trainer: wizardry", value: 80 },
  { label: "Trainer: faith", value: 81 },
  { label: "Trainer: slash", value: 82 },
  { label: "Trainer: blunt", value: 83 },
  { label: "Trainer: pierce", value: 84 },
  { label: "Trainer: ranged", value: 85 },
  { label: "Tunneler/Earthquake", value: 86 },
  { label: "Trainer: deikhan", value: 87 },
  { label: "Ram", value: 88 },
  { label: "Insulter", value: 89 },
  { label: "Kraken", value: 90 },
  { label: "ascallion", value: 91 },
  { label: "electric eel", value: 92 },
  { label: "poison hit", value: 93 },
  { label: "Belimus", value: 94 },
  { label: "Siren", value: 95 },
  { label: "Lamp-Lighter", value: 96 },
  { label: "Leper", value: 97 },
  { label: "Air Magi", value: 98 },
  { label: "Water Magi", value: 99 },
  { label: "Earth Magi", value: 100 },
  { label: "Fire Magi", value: 101 },
  { label: "Sorcerer", value: 102 },
  { label: "Faction-Faery", value: 103 },
  { label: "Trainer: brawling", value: 104 },
  { label: "Trainer: mage/thief", value: 105 },
  { label: "Trainer: meditation (monk)", value: 106 },
  { label: "Trainer: survival", value: 107 },
  { label: "Trainer: armadillo", value: 108 },
  { label: "Trainer: animal", value: 109 },
  { label: "Trainer: aegis", value: 110 },
  { label: "Trainer: shaman rites", value: 111 },
  { label: "frost giant warrior", value: 112 },
  { label: "librarian", value: 113 },
  { label: "rumormonger", value: 114 },
  { label: "Trainer: mage", value: 115 },
  { label: "Trainer: monk", value: 116 },
  { label: "Trainer: cleric", value: 117 },
  { label: "Trainer: thief", value: 118 },
  { label: "Trainer: plants", value: 119 },
  { label: "Trainer: soldiering", value: 120 },
  { label: "Trainer: blacksmithing", value: 121 },
  { label: "Trainer: deikhan fight", value: 122 },
  { label: "Trainer: mounted", value: 123 },
  { label: "Trainer: deikhan guardian", value: 124 },
  { label: "Trainer: deikhan cures", value: 125 },
  { label: "Trainer: deikhan wrath", value: 126 },
  { label: "Trainer: leverage", value: 127 },
  { label: "Trainer: mindbody", value: 128 },
  { label: "grimhaven posse", value: 129 },
  { label: "grimhaven hooker", value: 130 },
  { label: "Trainer: focused attacks", value: 131 },
  { label: "Corpse Muncher", value: 132 },
  { label: "Trainer: barehand", value: 133 },
  { label: "Trainer: thief fight", value: 134 },
  { label: "Trainer: poisons", value: 135 },
  { label: "Trainer: frog", value: 136 },
  { label: "Trainer: shaman alchemy", value: 137 },
  { label: "Trainer: skunk", value: 138 },
  { label: "Trainer: spider", value: 139 },
  { label: "Trainer: control", value: 140 },
  { label: "Trainer: ritualism", value: 141 },
  { label: "paladin patrol", value: 142 },
  { label: "shaman guildmaster", value: 143 },
  { label: "Trainer: combat", value: 144 },
  { label: "Trainer: stealth", value: 145 },
  { label: "Trainer: traps", value: 146 },
  { label: "Newbie Equipper", value: 147 },
  { label: "Trainer: lore", value: 148 },
  { label: "Trainer: theology", value: 149 },
  { label: "attuner", value: 150 },
  { label: "paralyze gaze", value: 151 },
  { label: "Doppleganger/Mimic", value: 152 },
  { label: "Tusker/Goring", value: 153 },
  { label: "Fish Tracker", value: 154 },
  { label: "Bank Guard", value: 155 },
  { label: "Fishing Boat Captain", value: 156 },
  { label: "Coroner", value: 157 },
  { label: "Guild Registrar", value: 158 },
  { label: "Trainer: defense", value: 159 },
  { label: "Scared Kid", value: 160 },
  { label: "Corporate Assistant", value: 161 },
  { label: "Trainer: psionics", value: 162 },
  { label: "Divination Man", value: 163 },
  { label: "Trainer: healing abilities", value: 164 },
  { label: "Gardener", value: 165 },
  { label: "Brightmoon Archer", value: 166 },
  { label: "Money Train", value: 167 },
  { label: "Adventurer", value: 168 },
  { label: "Trainer: iron body", value: 169 },
  { label: "Tudy", value: 170 },
  { label: "Barmaid", value: 171 },
  { label: "tattoo artist", value: 172 },
  { label: "casino elevator operator", value: 173 },
  { label: "casino elevator guard", value: 174 },
  { label: "commodity maker", value: 175 },
  { label: "lottery redeemer", value: 176 },
  { label: "konastis's guard", value: 177 },
  { label: "hold'em player", value: 178 },
  { label: "postman", value: 179 },
  { label: "poison bite", value: 180 },
  { label: "riddling tree", value: 181 },
  { label: "fireman", value: 182 },
  { label: "mimic", value: 183 },
  { label: "archer", value: 184 },
  { label: "peddler", value: 185 },
  { label: "limb disposer", value: 186 },
  { label: "stat surgeon", value: 187 },
  { label: "shipping official", value: 188 },
  { label: "loan shark", value: 189 },
  { label: "trolley driver", value: 190 },
  { label: "property clerk", value: 191 },
  { label: "banker", value: 192 },
  { label: "prison janitor", value: 193 },
  { label: "cat", value: 194 },
  { label: "taxman", value: 195 },
  { label: "Trainer: advanced adventuring", value: 196 },
  { label: "amber janitor", value: 197 },
  { label: "brightmoon janitor", value: 198 },
  { label: "garbage convoy", value: 199 },
  { label: "signmaker", value: 200 },
  { label: "butler", value: 201 },
  { label: "leper hunter", value: 202 },
  { label: "auctioneer", value: 203 },
  { label: "loan manager", value: 204 },
  { label: "bee death", value: 205 },
  { label: "hero faerie", value: 206 },
  { label: "Brick Collector", value: 207 },
  { label: "caretaker", value: 208 },
  { label: "ship captain", value: 209 },
  { label: "aggro follower", value: 210 },
  { label: "central banker", value: 211 },
  { label: "cannon loader", value: 212 },
  { label: "id card provider", value: 213 },
  { label: "Target dummy", value: 214 },
  { label: "fruit scavenger", value: 215 },
  { label: "commodity trader", value: 216 },
  { label: "ration factory", value: 217 },
  { label: "pet veterinarian", value: 218 },
  { label: "lagomorph", value: 219 },
  { label: "Trainer: Offense", value: 220 },
  { label: "Tailor", value: 221 },
  { label: "Blacksmith", value: 222 },
];
