import type { EnumEntry } from "../types/enums.ts";

export const OBJ_SPEC_PROCS: EnumEntry[] = [
  { label: "None", value: 0 },
  { label: "ballot box", value: 1 },
  { label: "bulletin board", value: 2 },
  { label: "note dispenser", value: 3 },
  { label: "statue of feeding", value: 4 },
  { label: "pager", value: 5 },
  { label: "ear muffs", value: 6 },
  { label: "Jewel of Judgment", value: 7 },
  { label: "Gwarthir", value: 8 },
  { label: "vending machine", value: 9 },
  { label: "Orb of Destruction", value: 10 },
  { label: "War Maker", value: 11 },
  { label: "Weapon: disruption", value: 12 },
  { label: "Weapon: fumbler", value: 13 },
  { label: "ladder", value: 14 },
  { label: "regeneration", value: 15 },
  { label: "Weapon: bonebreaker", value: 16 },
  { label: "Glowing Cutlass", value: 17 },
  { label: "poison whip", value: 18 },
  { label: "magic gills", value: 19 },
  { label: "recharging wand", value: 20 },
  { label: "rainbow bridge", value: 21 },
  { label: "Hunting Dagger", value: 22 },
  { label: "flame weapon", value: 23 },
  { label: "frost weapon", value: 24 },
  { label: "food&drink", value: 25 },
  { label: "crystal ball", value: 26 },
  { label: "Orb of Teleportation", value: 27 },
  { label: "Weather Armor", value: 28 },
  { label: "caravan wagon", value: 29 },
  { label: "Bleed Chair", value: 30 },
  { label: "Harm Chair", value: 31 },
  { label: "Dragon Slayer", value: 32 },
  { label: "Blood Drainer", value: 33 },
  { label: "Stone Altar", value: 34 },
  { label: "Bone Staff", value: 35 },
  { label: "Bloodspike", value: 36 },
  { label: "behir horn item", value: 37 },
  { label: "Newbie Helper", value: 38 },
  { label: "pirate hat dispenser", value: 39 },
  { label: "Blood Bowl", value: 40 },
  { label: "feather fall", value: 41 },
  { label: "wicked dagger", value: 42 },
  { label: "poison sap dagger", value: 43 },
  { label: "blinder weapon", value: 44 },
  { label: "mana drain weapon", value: 45 },
  { label: "tequila cutlass", value: 46 },
  { label: "daySword", value: 47 },
  { label: "nightBlade", value: 48 },
  { label: "Lightning Rod", value: 49 },
  { label: "Thief Quest Weapon", value: 50 },
  { label: "Sciren's Suffocation", value: 51 },
  { label: "energy blade", value: 52 },
  { label: "Viper Weapon (poison)", value: 53 },
  { label: "trolley", value: 54 },
  { label: "Stone Skin Amulet", value: 55 },
  { label: "Razor Glove", value: 56 },
  { label: "ShadowSlayer", value: 57 },
  { label: "Squirt Gun", value: 58 },
  { label: "Glory Weapon", value: 59 },
  { label: "Elemental Weapon", value: 60 },
  { label: "Life Leech Glove", value: 61 },
  { label: "Mechanical Wings", value: 62 },
  { label: "Key in Knife", value: 63 },
  { label: "Teleport Vial", value: 64 },
  { label: "Sun Circle Amulet", value: 65 },
  { label: "Better Vender", value: 66 },
  { label: "Mine Cart", value: 67 },
  { label: "Switchtrack", value: 68 },
  { label: "vorpal", value: 69 },
  { label: "Berserker Weapon", value: 70 },
  { label: "Travel Gear", value: 71 },
  { label: "Maquahuitl", value: 72 },
  { label: "Randomizer", value: 73 },
  { label: "Blunt/Pierce", value: 74 },
  { label: "Dual Style Weapon", value: 75 },
  { label: "Mana Burn Robe", value: 76 },
  { label: "Chrism: minor heal", value: 77 },
  { label: "Chrism: bless hold item", value: 78 },
  { label: "Chrism: vitality restore", value: 79 },
  { label: "Chipped Tooth Food Item", value: 80 },
  { label: "Goofers Dust", value: 81 },
  { label: "teleport ring", value: 82 },
  { label: "self repairing", value: 83 },
  { label: "undead spewing portal", value: 84 },
  { label: "Amulet of Aeth Koralm", value: 85 },
  { label: "fire glove", value: 86 },
  { label: "Shaman's Totem Mask", value: 87 },
  { label: "perma death monument", value: 88 },
  { label: "fishing boat", value: 89 },
  { label: "Splintered Club", value: 90 },
  { label: "Suffocation Glove", value: 91 },
  { label: "Force", value: 92 },
  { label: "trophy board", value: 93 },
  { label: "shopinfo board", value: 94 },
  { label: "Sonic Blast", value: 95 },
  { label: "highrollers board", value: 96 },
  { label: "faction score board", value: 97 },
  { label: "fragile arrow", value: 98 },
  { label: "Weapon: Starfire", value: 99 },
  { label: "Sheath: Starfire", value: 100 },
  { label: "Teleport Rescue Item", value: 101 },
  { label: "Deikhan Sword", value: 102 },
  { label: "black sun", value: 103 },
  { label: "poison cutlass", value: 104 },
  { label: "unholy cutlass", value: 105 },
  { label: "ghostly shiv", value: 106 },
  { label: "hammer set: peke", value: 107 },
  { label: "hammer set: copsi", value: 108 },
  { label: "hammer set: pendant", value: 109 },
  { label: "blizzard ring", value: 110 },
  { label: "frost spear", value: 111 },
  { label: "ice staff", value: 112 },
  { label: "heart of the arctic", value: 113 },
  { label: "frost armor", value: 114 },
  { label: "telekinesis glove", value: 115 },
  { label: "Symbol of the Blinding Light", value: 116 },
  { label: "Weapon: Unmaker", value: 117 },
  { label: "Chromatic Weapon", value: 118 },
  { label: "spawning object: open", value: 119 },
  { label: "Energy Shield: generator", value: 120 },
  { label: "Energy Shield: shield", value: 121 },
  { label: "teleporting object", value: 122 },
  { label: "holy cutlass", value: 123 },
  { label: "fortune cookie", value: 124 },
  { label: "Fireball Weapon", value: 125 },
  { label: "Fire Shield", value: 126 },
  { label: "Finns Gaff", value: 127 },
  { label: "stim pack", value: 128 },
  { label: "lottery ticket", value: 129 },
  { label: "lycanthropy cure", value: 130 },
  { label: "vella key join", value: 131 },
  { label: "Gnath well bucket", value: 132 },
  { label: "sweeps scratch", value: 133 },
  { label: "sweeps split join", value: 134 },
  { label: "graffiti maker", value: 135 },
  { label: "graffiti object", value: 136 },
  { label: "statue arm twist", value: 137 },
  { label: "sticker bush", value: 138 },
  { label: "switch object", value: 139 },
  { label: "gnome tenderizer", value: 140 },
  { label: "Marukalia", value: 141 },
  { label: "lightsaber", value: 142 },
  { label: "broken bottle", value: 143 },
  { label: "Demon Slayer", value: 144 },
  { label: "Astral Walk", value: 145 },
  { label: "Minor Astral Walk", value: 146 },
  { label: "Portal", value: 147 },
  { label: "brick quest scorecard", value: 148 },
  { label: "EQ Combo Casting", value: 149 },
  { label: "Skittish Object", value: 150 },
  { label: "Dwarf Power", value: 151 },
  { label: "Mob Spawn Grab", value: 152 },
  { label: "rubik's cube", value: 153 },
  { label: "Immortal Exchange Computer", value: 154 },
  { label: "liquid source", value: 155 },
  { label: "of many potions", value: 156 },
  { label: "Shadow Weapon", value: 157 },
  { label: "Living Vines", value: 158 },
  { label: "Piety Regen", value: 159 },
  { label: "DK Sword", value: 160 },
  { label: "Molten Weapon", value: 161 },
  { label: "Glacial Weapon", value: 162 },
  { label: "satyr shrine", value: 163 },
];
