import type { EnumEntry } from "./types.ts";

export const ROOM_SPEC_PROCS: EnumEntry[] = [
  { label: "None", value: 0 },
  { label: "Bank Main Entrance", value: 2 },
  { label: "Bank Vault", value: 3 },
  { label: "Secret Doors", value: 4 },
  { label: "Secret Portal Doors", value: 5 },
  { label: "Whirlpool", value: 6 },
  { label: "Bank Room", value: 7 },
  { label: "belimus Blow Hole", value: 8 },
  { label: "belimus Lungs", value: 9 },
  { label: "belimus Stomach", value: 10 },
  { label: "belimus Throat", value: 11 },
  { label: "boulder Room", value: 12 },
  { label: "dayGate Room", value: 14 },
  { label: "duergar Water", value: 15 },
  { label: "emergency room", value: 17 },
  { label: "healing room", value: 19 },
  { label: "monk Quest Proc Fall", value: 20 },
  { label: "monk Quest Proc Land", value: 21 },
  { label: "moonGate Room", value: 22 },
  { label: "noise Boom", value: 23 },
  { label: "oft frequented room", value: 24 },
  { label: "prison Dump", value: 26 },
  { label: "random Mob Distribution", value: 27 },
  { label: "sleep Tag Control", value: 28 },
  { label: "sleep Tag Room", value: 29 },
  { label: "slide", value: 30 },
  { label: "the Knot", value: 31 },
  { label: "weird Circle", value: 32 },
  { label: "blazingroom", value: 33 },
];
