import type { EnumEntry } from "./types.ts";

export const SECTOR_TYPES: EnumEntry[] = [
  { label: "Subarctic", value: 0 },
  { label: "Arctic Waste", value: 1 },
  { label: "Arctic City", value: 2 },
  { label: "Arctic Road", value: 3 },
  { label: "Tundra", value: 4 },
  { label: "Arctic Mountains", value: 5 },
  { label: "Arctic Forest", value: 6 },
  { label: "Arctic Marsh", value: 7 },
  { label: "Arctic River Surface", value: 8 },
  { label: "Iceflow", value: 9 },
  { label: "Cold Beach", value: 10 },
  { label: "Solid Ice", value: 11 },
  { label: "Arctic Building", value: 12 },
  { label: "Arctic Cave", value: 13 },
  { label: "Arctic Atmosphere", value: 14 },
  { label: "Arctic Climbing", value: 15 },
  { label: "Arctic Forest Road", value: 16 },
  { label: "Plains", value: 17 },
  { label: "Temperate City", value: 18 },
  { label: "Temperate Road", value: 19 },
  { label: "Grasslands", value: 20 },
  { label: "Temperate Hills", value: 21 },
  { label: "Temperate Mountains", value: 22 },
  { label: "Temperate Forest", value: 23 },
  { label: "Temperate Swamp", value: 24 },
  { label: "Temperate Ocean", value: 25 },
  { label: "Temperate River Surface", value: 26 },
  { label: "Temperate Underwater", value: 27 },
  { label: "Temperate Beach", value: 28 },
  { label: "Temperate Building", value: 29 },
  { label: "Temperate Cave", value: 30 },
  { label: "Temperate Atmosphere", value: 31 },
  { label: "Temperate Climbing", value: 32 },
  { label: "Temperate Forest Road", value: 33 },
  { label: "Desert", value: 34 },
  { label: "Savannah", value: 35 },
  { label: "Veldt", value: 36 },
  { label: "Tropical City", value: 37 },
  { label: "Tropical Road", value: 38 },
  { label: "Jungle", value: 39 },
  { label: "Rainforest", value: 40 },
  { label: "Tropical Hills", value: 41 },
  { label: "Tropical Mountains", value: 42 },
  { label: "Volcano Lava", value: 43 },
  { label: "Tropical Swamp", value: 44 },
  { label: "Tropical Ocean", value: 45 },
  { label: "Tropical River Surface", value: 46 },
  { label: "Tropical Underwater", value: 47 },
  { label: "Tropical Beach", value: 48 },
  { label: "Tropical Building", value: 49 },
  { label: "Tropical Cave", value: 50 },
  { label: "Tropical Atmosphere", value: 51 },
  { label: "Tropical Climbing", value: 52 },
  { label: "Rainforest Road", value: 53 },
  { label: "Astral Ethereal", value: 54 },
  { label: "Solid Rock", value: 55 },
  { label: "Fire", value: 56 },
  { label: "Inside Mob", value: 57 },
  { label: "Fire Atmosphere", value: 58 },
  { label: "Make Fly", value: 59 },
  { label: "Dead Woods", value: 60 },
];
