// Spell/skill file IDs from mapSpellnumToFile() in spell_num.cc.
// Used by APPLY_SPELL (file value 23) mod1 field.

import type { EnumEntry } from "./types.ts";

export const SPELL_TYPES: EnumEntry[] = [
  { label: "Gust", value: 0 },
  { label: "Sling Shot", value: 1 },
  { label: "Gusher", value: 2 },
  { label: "Hands Of Flame", value: 3 },
  { label: "Mystic Darts", value: 4 },
  { label: "Flare", value: 5 },
  { label: "Sorcerers Globe", value: 6 },
  { label: "Faerie Fire", value: 7 },
  { label: "Illuminate", value: 8 },
  { label: "Detect Magic", value: 9 },
  { label: "Stunning Arrow", value: 10 },
  { label: "Materialize", value: 11 },
  { label: "Protection From Earth", value: 12 },
  { label: "Protection From Air", value: 13 },
  { label: "Protection From Fire", value: 14 },
  { label: "Protection From Water", value: 15 },
  { label: "Protection From Energy", value: 16 },
  { label: "Pebble Spray", value: 17 },
  { label: "Arctic Blast", value: 18 },
  { label: "Color Spray", value: 19 },
  { label: "Infravision", value: 20 },
  { label: "Identify", value: 21 },
  { label: "Powerstone", value: 22 },
  { label: "Faerie Fog", value: 23 },
  { label: "Teleport", value: 24 },
  { label: "Sense Life", value: 25 },
  { label: "Calm", value: 26 },
  { label: "Accelerate", value: 27 },
  { label: "Dust Storm", value: 28 },
  { label: "Levitate", value: 29 },
  { label: "Feathery Descent", value: 30 },
  { label: "Stealth", value: 31 },
  { label: "Granite Fists", value: 32 },
  { label: "Icy Grip", value: 33 },
  { label: "Gills Of Flesh", value: 34 },
  { label: "Telepathy", value: 36 },
  { label: "Fear", value: 37 },
  { label: "Slumber", value: 38 },
  { label: "Conjure Elemental Earth", value: 39 },
  { label: "Conjure Elemental Air", value: 40 },
  { label: "Conjure Elemental Fire", value: 41 },
  { label: "Conjure Elemental Water", value: 42 },
  { label: "Dispel Magic", value: 43 },
  { label: "Enhance Weapon", value: 44 },
  { label: "Galvanize", value: 45 },
  { label: "Detect Invisibility", value: 46 },
  { label: "Dispel Invisible", value: 47 },
  { label: "Tornado", value: 48 },
  { label: "Sand Blast", value: 49 },
  { label: "Ice Storm", value: 50 },
  { label: "Blast Of Fury", value: 51 },
  { label: "Acid Blast", value: 52 },
  { label: "Fireball", value: 53 },
  { label: "Farlook", value: 54 },
  { label: "Falcon Wings", value: 55 },
  { label: "Invisibility", value: 56 },
  { label: "Ensorcer", value: 57 },
  { label: "Eyes Of Fertuman", value: 58 },
  { label: "Copy", value: 59 },
  { label: "Haste", value: 60 },
  { label: "Lightning Bolt", value: 62 },
  { label: "Chain Lightning", value: 63 },
  { label: "Immobilize", value: 66 },
  { label: "Suffocate", value: 67 },
  { label: "Flight", value: 68 },
  { label: "Antigravity", value: 69 },
  { label: "Divination", value: 73 },
  { label: "Shatter", value: 74 },
  { label: "Scribe", value: 75 },
  { label: "Spontaneous Generation", value: 76 },
  { label: "Meteor Swarm", value: 80 },
  { label: "Lava Stream", value: 81 },
  { label: "Stone Skin", value: 82 },
  { label: "Trail Seek", value: 83 },
  { label: "Lava Lance", value: 86 },
  { label: "Inferno", value: 87 },
  { label: "Hellfire", value: 88 },
  { label: "Flaming Flesh", value: 89 },
  { label: "Flaming Sword", value: 90 },
  { label: "Energy Drain", value: 94 },
  { label: "Atomize", value: 95 },
  { label: "Animate", value: 97 },
  { label: "Bind", value: 98 },
  { label: "Ethereal Gate", value: 99 },
  { label: "Knot", value: 100 },
  { label: "Fumble", value: 102 },
  { label: "True Sight", value: 103 },
  { label: "Cloud Of Concealment", value: 104 },
  { label: "Polymorph", value: 105 },
  { label: "Silence", value: 106 },
  { label: "Watery Grave", value: 110 },
  { label: "Tsunami", value: 111 },
  { label: "Breath Of Sarahage", value: 112 },
  { label: "Plasma Mirror", value: 113 },
  { label: "Garmul's Tail", value: 114 },
  { label: "Heal Light", value: 126 },
  { label: "Harm Light", value: 127 },
  { label: "Create Food", value: 128 },
  { label: "Create Water", value: 129 },
  { label: "Armor", value: 130 },
  { label: "Bless", value: 131 },
  { label: "Clot", value: 132 },
  { label: "Rain Brimstone", value: 133 },
  { label: "Heal Serious", value: 134 },
  { label: "Harm Serious", value: 135 },
  { label: "Sterilize", value: 136 },
  { label: "Expel", value: 137 },
  { label: "Cure Disease", value: 138 },
  { label: "Curse", value: 140 },
  { label: "Remove Curse", value: 141 },
  { label: "Cure Poison", value: 142 },
  { label: "Heal Critical", value: 143 },
  { label: "Salve", value: 144 },
  { label: "Poison", value: 145 },
  { label: "Harm Critical", value: 146 },
  { label: "Infect", value: 147 },
  { label: "Refresh", value: 148 },
  { label: "Numb", value: 149 },
  { label: "Disease", value: 150 },
  { label: "Flamestrike", value: 151 },
  { label: "Plague Of Locusts", value: 152 },
  { label: "Cure Blindness", value: 153 },
  { label: "Summon", value: 154 },
  { label: "Heal", value: 155 },
  { label: "Paralyze Limb", value: 156 },
  { label: "Word Of Recall", value: 157 },
  { label: "Harm", value: 158 },
  { label: "Blindness", value: 159 },
  { label: "Pillar Of Salt", value: 165 },
  { label: "Earthquake", value: 166 },
  { label: "Call Lightning", value: 167 },
  { label: "Spontaneous Combust", value: 168 },
  { label: "Bleed", value: 178 },
  { label: "Paralyze", value: 179 },
  { label: "Bone Breaker", value: 180 },
  { label: "Wither Limb", value: 181 },
  { label: "Sanctuary", value: 185 },
  { label: "Cure Paralysis", value: 186 },
  { label: "Second Wind", value: 187 },
  { label: "Heroes Feast", value: 192 },
  { label: "Astral Walk", value: 193 },
  { label: "Portal", value: 194 },
  { label: "Heal Full", value: 198 },
  { label: "Heal Critical Spray", value: 199 },
  { label: "Heal Spray", value: 200 },
  { label: "Heal Full Spray", value: 201 },
  { label: "Restore Limb", value: 202 },
  { label: "Knit Bone", value: 203 },
  { label: "Relive", value: 204 },
  { label: "Crusade", value: 205 },
  { label: "Slam", value: 217 },
  { label: "Bash", value: 218 },
  { label: "Headbutt", value: 219 },
  { label: "Rescue", value: 220 },
  { label: "Blacksmithing", value: 221 },
  { label: "Disarm", value: 222 },
  { label: "Berserk", value: 223 },
  { label: "Switch Opponents", value: 224 },
  { label: "Bodyslam", value: 225 },
  { label: "Kneestrike", value: 226 },
  { label: "Defensive Trance", value: 227 },
  { label: "Weapon Retention", value: 228 },
  { label: "Shove", value: 229 },
  { label: "Retreat", value: 230 },
  { label: "Grapple", value: 234 },
  { label: "Stomp", value: 235 },
  { label: "Brawl Avoidance", value: 236 },
  { label: "Close Quarters Fighting", value: 237 },
  { label: "Doorbash", value: 238 },
  { label: "Deathstroke", value: 239 },
  { label: "Taunting", value: 240 },
  { label: "Debride", value: 241 },
  { label: "Hiking", value: 266 },
  { label: "Forage", value: 268 },
  { label: "Seekwater", value: 269 },
  { label: "Transform Limb", value: 270 },
  { label: "Beast Soother", value: 271 },
  { label: "Track", value: 272 },
  { label: "Root Control", value: 273 },
  { label: "Befriend Beast", value: 277 },
  { label: "Transfix", value: 278 },
  { label: "Skinning", value: 279 },
  { label: "Living Vines", value: 281 },
  { label: "Beast Summon", value: 282 },
  { label: "Barkskin", value: 283 },
  { label: "Sticks To Snakes", value: 292 },
  { label: "Stormy Skies", value: 293 },
  { label: "Tree Walk", value: 294 },
  { label: "Beast Charm", value: 298 },
  { label: "Shapeshift", value: 299 },
  { label: "Concealment", value: 303 },
  { label: "Apply Herbs", value: 304 },
  { label: "Divine", value: 308 },
  { label: "Encamp", value: 310 },
  { label: "Fishlore", value: 311 },
  { label: "Aura Of Absolution", value: 322 },
  { label: "Aura Absolution", value: 323 },
  { label: "Aura Of Vengeance", value: 324 },
  { label: "Aura Vengeance", value: 325 },
  { label: "Heal Light", value: 326 },
  { label: "Chivalry", value: 327 },
  { label: "Armor", value: 328 },
  { label: "Bless", value: 329 },
  { label: "Bash-deikhan", value: 330 },
  { label: "Expel", value: 332 },
  { label: "Clot", value: 333 },
  { label: "Sterilize", value: 335 },
  { label: "Remove Curse", value: 336 },
  { label: "Curse", value: 337 },
  { label: "Rescue", value: 338 },
  { label: "Smite", value: 339 },
  { label: "Infect", value: 340 },
  { label: "Cure Disease", value: 341 },
  { label: "Create Food", value: 342 },
  { label: "Create Water", value: 343 },
  { label: "Heal Serious", value: 344 },
  { label: "Cure Poison", value: 345 },
  { label: "Charge", value: 346 },
  { label: "Harm Serious", value: 347 },
  { label: "Poison", value: 348 },
  { label: "Disarm", value: 349 },
  { label: "Heal Critical", value: 350 },
  { label: "Harm Critical", value: 351 },
  { label: "Harm Light", value: 352 },
  { label: "Switch Opponents", value: 355 },
  { label: "Retreat", value: 356 },
  { label: "Shove", value: 357 },
  { label: "2h Specialization", value: 358 },
  { label: "Ride", value: 359 },
  { label: "Calm Mount", value: 360 },
  { label: "Train Mount", value: 361 },
  { label: "Advanced Riding", value: 362 },
  { label: "Ride Domestic", value: 363 },
  { label: "Ride Non-domestic", value: 364 },
  { label: "Ride Winged", value: 365 },
  { label: "Ride Exotic", value: 366 },
  { label: "Heroes Feast", value: 367 },
  { label: "Refresh", value: 368 },
  { label: "Synostodweomer", value: 369 },
  { label: "Divine Grace", value: 370 },
  { label: "Divine Rescue", value: 371 },
  { label: "Guardians Light", value: 372 },
  { label: "Salve", value: 374 },
  { label: "Lay Hands", value: 375 },
  { label: "Harm", value: 379 },
  { label: "Numb", value: 380 },
  { label: "Aura Of Might", value: 383 },
  { label: "Aura Might", value: 384 },
  { label: "Aura Of Regeneration", value: 385 },
  { label: "Aura Regeneration", value: 386 },
  { label: "Aura Of The Guardian", value: 387 },
  { label: "Aura Guardian", value: 388 },
  { label: "Focused Avoidance", value: 390 },
  { label: "Yoginsa", value: 397 },
  { label: "Cintai", value: 398 },
  { label: "Oomlat Philosophy", value: 399 },
  { label: "Kick", value: 400 },
  { label: "Advanced Kicking", value: 401 },
  { label: "Disarm", value: 402 },
  { label: "Groundfighting", value: 403 },
  { label: "Chop", value: 404 },
  { label: "Springleap", value: 405 },
  { label: "Dufali", value: 406 },
  { label: "Retreat", value: 407 },
  { label: "Snofalte", value: 408 },
  { label: "Counter Move", value: 409 },
  { label: "Switch Opponents", value: 410 },
  { label: "Jirin", value: 411 },
  { label: "Kubo", value: 412 },
  { label: "Catfall", value: 413 },
  { label: "Catleap", value: 414 },
  { label: "Wohlin Meditation", value: 423 },
  { label: "Voplat", value: 424 },
  { label: "Blindfighting", value: 425 },
  { label: "Chi", value: 426 },
  { label: "Quivering Palm", value: 435 },
  { label: "Critical Hitting", value: 436 },
  { label: "Bonebreak", value: 446 },
  { label: "Defenestrate", value: 447 },
  { label: "Feign Death", value: 448 },
  { label: "Blur", value: 449 },
  { label: "Hurl", value: 461 },
  { label: "Shoulder Throw", value: 462 },
  { label: "Chain Attack", value: 463 },
  { label: "Barehand Specialization", value: 474 },
  { label: "Swindle", value: 482 },
  { label: "Sneak", value: 483 },
  { label: "Stab", value: 484 },
  { label: "Retreat", value: 485 },
  { label: "Kick", value: 486 },
  { label: "Picklock", value: 487 },
  { label: "Backstab", value: 488 },
  { label: "Search", value: 489 },
  { label: "Spy", value: 490 },
  { label: "Switch Opponents", value: 491 },
  { label: "Steal", value: 492 },
  { label: "Detect Trap", value: 493 },
  { label: "Subterfuge", value: 494 },
  { label: "Disarm Trap", value: 495 },
  { label: "Cudgel", value: 496 },
  { label: "Hide", value: 497 },
  { label: "Poison Weapons", value: 498 },
  { label: "Disguise", value: 499 },
  { label: "Dodge", value: 500 },
  { label: "Garrotte", value: 501 },
  { label: "Set Container Trap", value: 502 },
  { label: "Dual Wield", value: 503 },
  { label: "Disarm", value: 504 },
  { label: "Counter Steal", value: 505 },
  { label: "Set Door Trap", value: 506 },
  { label: "Set Mine Trap", value: 507 },
  { label: "Set Grenade Trap", value: 508 },
  { label: "Ritualism", value: 523 },
  { label: "Flatulence", value: 524 },
  { label: "Boiling Blood", value: 525 },
  { label: "Stupidity", value: 526 },
  { label: "Celerite", value: 527 },
  { label: "Death Wave", value: 528 },
  { label: "Distort", value: 529 },
  { label: "Soul Twister", value: 530 },
  { label: "Squish", value: 531 },
  { label: "Coronary", value: 532 },
  { label: "Legba's Guidance", value: 533 },
  { label: "Djalla's Protection", value: 534 },
  { label: "Sense Presence", value: 535 },
  { label: "Detect Shadow", value: 536 },
  { label: "Raze", value: 537 },
  { label: "Intimidate", value: 538 },
  { label: "Romble", value: 539 },
  { label: "Chrism", value: 540 },
  { label: "Cheval", value: 541 },
  { label: "Hypnosis", value: 542 },
  { label: "Lich Touch", value: 543 },
  { label: "Death Mist", value: 544 },
  { label: "Shadow Walk", value: 545 },
  { label: "Clarity", value: 546 },
  { label: "Sacrifice", value: 547 },
  { label: "Aqualung", value: 548 },
  { label: "Aquatic Blast", value: 549 },
  { label: "Thornflesh", value: 550 },
  { label: "Enthrall Ghoul", value: 551 },
  { label: "Enthrall Ghast", value: 552 },
  { label: "Enthrall Demon", value: 553 },
  { label: "Enthrall Spectre", value: 554 },
  { label: "Shield Of Mists", value: 555 },
  { label: "Create Iron Golem", value: 556 },
  { label: "Create Diamond Golem", value: 557 },
  { label: "Dancing Bones", value: 558 },
  { label: "Control Undead", value: 559 },
  { label: "Resurrection", value: 560 },
  { label: "Voodoo", value: 561 },
  { label: "Brew", value: 562 },
  { label: "Vampiric Touch", value: 563 },
  { label: "Life Leech", value: 564 },
  { label: "Turn", value: 565 },
  { label: "Create Wood Golem", value: 566 },
  { label: "Create Rock Golem", value: 567 },
  { label: "Chase Spirits", value: 568 },
  { label: "Cleanse", value: 569 },
  { label: "Embalm", value: 570 },
  { label: "Sign", value: 576 },
  { label: "Swim", value: 577 },
  { label: "Know Undead", value: 578 },
  { label: "Know Veggie", value: 579 },
  { label: "Know Demon", value: 580 },
  { label: "Know Animal", value: 581 },
  { label: "Know Reptile", value: 582 },
  { label: "Know People", value: 583 },
  { label: "Know Giantkin", value: 584 },
  { label: "Know Other", value: 585 },
  { label: "Read Magic", value: 586 },
  { label: "Bandage", value: 587 },
  { label: "Climbing", value: 588 },
  { label: "Fast Heal", value: 589 },
  { label: "Evaluate", value: 590 },
  { label: "Tactics", value: 591 },
  { label: "Dissect", value: 592 },
  { label: "Defense", value: 593 },
  { label: "Offense", value: 594 },
  { label: "Wizardry", value: 596 },
  { label: "Meditate", value: 597 },
  { label: "Devotion", value: 601 },
  { label: "Penance", value: 602 },
  { label: "Slash Specialization", value: 611 },
  { label: "Riposte", value: 612 },
  { label: "Blunt Specialization", value: 630 },
  { label: "Pierce Specialization", value: 640 },
  { label: "Ranged Specialization", value: 648 },
  { label: "Fast Load", value: 649 },
  { label: "Slash Proficiency", value: 654 },
  { label: "Ranged Proficiency", value: 655 },
  { label: "Pierce Proficiency", value: 656 },
  { label: "Blunt Proficiency", value: 657 },
  { label: "Sharpen", value: 658 },
  { label: "Smooth", value: 659 },
  { label: "Barehand Proficiency", value: 660 },
  { label: "Attune", value: 661 },
  { label: "Charge Stave", value: 662 },
  { label: "Whittle", value: 663 },
  { label: "Parry", value: 664 },
  { label: "Spin", value: 665 },
  { label: "Dual Wield", value: 666 },
  { label: "Power Move", value: 667 },
  { label: "Alcoholism", value: 668 },
  { label: "Fishing", value: 669 },
  { label: "Earthmaw", value: 670 },
  { label: "Creeping Doom", value: 671 },
  { label: "Feral Wrath", value: 672 },
  { label: "Sky Spirit", value: 673 },
  { label: "Advanced Defense", value: 674 },
  { label: "Psionic Telepathy", value: 675 },
  { label: "Telepathic Sight", value: 676 },
  { label: "Telepathic Vision", value: 677 },
  { label: "Mind Focus", value: 678 },
  { label: "Psionic Blast", value: 679 },
  { label: "Mind Thrust", value: 680 },
  { label: "Psychic Crush", value: 681 },
  { label: "Kinetic Wave", value: 682 },
  { label: "Mind Preservation", value: 683 },
  { label: "Telekinesis", value: 684 },
  { label: "Butcher", value: 685 },
  { label: "Slit", value: 686 },
  { label: "Healing Grasp", value: 687 },
  { label: "Mana", value: 688 },
  { label: "Iron Fist", value: 689 },
  { label: "Iron Flesh", value: 690 },
  { label: "Iron Skin", value: 691 },
  { label: "Iron Bones", value: 692 },
  { label: "Iron Muscles", value: 693 },
  { label: "Iron Legs", value: 694 },
  { label: "Iron Will", value: 695 },
  { label: "Mage Repair", value: 696 },
  { label: "Deikhan Repair", value: 698 },
  { label: "Cleric Repair", value: 699 },
  { label: "Monk Repair", value: 700 },
  { label: "Shaman Repair", value: 701 },
  { label: "Thief Repair", value: 702 },
  { label: "Mend", value: 703 },
  { label: "Advanced Blacksmithing", value: 704 },
  { label: "Psionic Drain", value: 705 },
  { label: "Trip", value: 706 },
  { label: "Enliven", value: 707 },
  { label: "Plant", value: 708 },
  { label: "Set Arrow Trap", value: 710 },
  { label: "Lumberjack", value: 711 },
  { label: "Gutter Cant", value: 712 },
  { label: "Gnoll Jargon", value: 713 },
  { label: "Troglodyte Pidgin", value: 714 },
  { label: "Trollish", value: 715 },
  { label: "Bullycroak", value: 716 },
  { label: "Avian", value: 717 },
  { label: "Fish Burble", value: 718 },
  { label: "Common", value: 719 },
  { label: "Cook", value: 724 },
  { label: "Advanced Offense", value: 730 },
  { label: "Toughness", value: 731 },
  { label: "Inevitability", value: 732 },
  { label: "Dimensional Fold", value: 733 },
  { label: "2h Specialization", value: 734 },
  { label: "Advanced Berserking", value: 735 },
  { label: "Bloodlust", value: 736 },
  { label: "Whirlwind", value: 737 },
  { label: "Rally", value: 738 },
  { label: "Focus Attack", value: 739 },
  { label: "Fortify", value: 740 },
  { label: "Shock Cavalry", value: 741 },
  { label: "Orient Mount", value: 742 },
  { label: "Pierce Resistances", value: 743 },
  { label: "Disease", value: 2500 },
  { label: "Combat", value: 2501 },
  { label: "Pet", value: 2502 },
  { label: "Transformed Hands", value: 2503 },
  { label: "Transformed Arms", value: 2504 },
  { label: "Transformed Legs", value: 2505 },
  { label: "Transformed Head", value: 2506 },
  { label: "Transformed Neck", value: 2507 },
  { label: "Transformed Limb", value: 2508 },
  { label: "Dummy", value: 2509 },
  { label: "Drunk", value: 2510 },
  { label: "Newbie", value: 2511 },
  { label: "Skill Attempt", value: 2512 },
  { label: "Free Deaths", value: 2513 },
  { label: "Test Fight Mob", value: 2514 },
  { label: "Drug", value: 2515 },
  { label: "Orphan Pet", value: 2516 },
  { label: "Playerkill", value: 2517 },
  { label: "Horseowned", value: 2518 },
  { label: "Thrall", value: 2519 },
  { label: "Charm", value: 2520 },
  { label: "Playerloot", value: 2521 },
  { label: "Growth Potion", value: 2522 },
  { label: "Wary", value: 2523 },
  { label: "Defected", value: 2524 },
  { label: "Offer", value: 2525 },
  { label: "Object Used", value: 2526 },
  { label: "Was Indoors", value: 2527 },
  { label: "Bitten By Vampire", value: 2528 },
  { label: "Immortal Blessing", value: 2529 },
  { label: "Aion Blessing", value: 2530 },
  { label: "Sidartha Blessing", value: 2531 },
  { label: "Damescena Blessing", value: 2532 },
  { label: "Boz Blessing", value: 2533 },
  { label: "Vasco Blessing", value: 2534 },
  { label: "Coral Blessing", value: 2535 },
  { label: "Bump Blessing", value: 2536 },
  { label: "Onslaught Blessing", value: 2537 },
  { label: "Dash Blessing", value: 2538 },
  { label: "Deirdre Blessing", value: 2539 },
  { label: "Garthagk Blessing", value: 2540 },
  { label: "Mercury Blessing", value: 2541 },
  { label: "Metrohep Blessing", value: 2542 },
  { label: "Magdalena Blessing", value: 2543 },
  { label: "Macross Blessing", value: 2544 },
  { label: "Pappy Blessing", value: 2545 },
  { label: "Preened", value: 2546 },
  { label: "Wet", value: 2547 },
  { label: "Staffa Blessing", value: 2548 },
  { label: "Unholy Wrath", value: 2549 },
  { label: "Guardians Light", value: 2550 },
  { label: "Holy Wrath", value: 2551 },
  { label: "Fortify", value: 2552 },
  { label: "Holy Beam", value: 2553 },
];
