trainerDict = {
    7 : {'code':"SPEC_TRAINER_AIR", 'name': "air", 'desc': "the art of Air Magic"},
    37 : {'code':"SPEC_TRAINER_ALCHEMY", 'name': "alchemy", 'desc': "the art of Alchemy"},
    38 : {'code':"SPEC_TRAINER_EARTH", 'name': "earth", 'desc': "the art of Earth Magic"},
    49 : {'code':"SPEC_TRAINER_FIRE", 'name': "fire", 'desc': "the art of Fire Magic"},
    63 : {'code':"SPEC_TRAINER_SORCERY", 'name': "sorcery", 'desc': "the art of Sorcery"},
    64 : {'code':"SPEC_TRAINER_SPIRIT", 'name': "spirit", 'desc': "the art of Spirit Magic"},
    65 : {'code':"SPEC_TRAINER_WATER", 'name': "water", 'desc': "the art of Water Magic"},
    66 : {'code':"SPEC_TRAINER_WRATH", 'name': "wrath", 'desc': "the Wrath of the Deities"},
    67 : {'code':"SPEC_TRAINER_AFFLICTIONS", 'name': "afflictions", 'desc': "the Art of Afflictions"},
    68 : {'code':"SPEC_TRAINER_CURE", 'name': "cures", 'desc': "the Healing Arts"},
    69 : {'code':"SPEC_TRAINER_HAND_OF_GOD", 'name': "hand", 'desc': "the Hand of the Deities"},
    70 : {'code':"SPEC_TRAINER_RANGER", 'name': "ranger", 'desc': "the Ways of the Ranger"},
    72 : {'code':"SPEC_TRAINER_LOOTING", 'name': "looting", 'desc': "Looting and Plundering"},
    73 : {'code':"SPEC_TRAINER_MURDER", 'name': "murder", 'desc': "about Deadly Murder"},
    74 : {'code':"SPEC_TRAINER_DUELING", 'name': "dueling", 'desc': "Dueling"},
    75 : {'code':"SPEC_TRAINER_ADVENTURING", 'name': "adventuring", 'desc': "Adventurers' Lore"},
    76 : {'code':"SPEC_TRAINER_WARRIOR", 'name': "warrior", 'desc': "the Ways of the Warrior"},
    80 : {'code':"SPEC_TRAINER_WIZARDRY", 'name': "wizardry", 'desc': "Wizardry"},
    81 : {'code':"SPEC_TRAINER_FAITH", 'name': "faith", 'desc': "Faith"},
    82 : {'code':"SPEC_TRAINER_SLASH", 'name': "slash", 'desc': "Slash Specialization"},
    83 : {'code':"SPEC_TRAINER_BLUNT", 'name': "blunt", 'desc': "Blunt Specialization"},
    84 : {'code':"SPEC_TRAINER_PIERCE", 'name': "pierce", 'desc': "Pierce Specialization"},
    85 : {'code':"SPEC_TRAINER_RANGED", 'name': "ranged", 'desc': "Ranged Specialization"},
    87 : {'code':"SPEC_TRAINER_DEIKHAN", 'name': "deikhan", 'desc': "the Ways of the Deikhan"},
    104 : {'code':"SPEC_TRAINER_BRAWLING", 'name': "brawling", 'desc': "Brawling Moves"},
    105 : {'code':"SPEC_TRAINER_SHAMAN_HEALING", 'name': "healing", 'desc': "about healing abilities for shaman"},
    106 : {'code':"SPEC_TRAINER_MEDITATION_MONK", 'name': "meditation", 'desc': "about Meditation"},
    108 : {'code':"SPEC_TRAINER_SHAMAN_ARMADILLO", 'name': "armadillo", 'desc': "about the Abilities of the Armadillo"},
    109 : {'code':"SPEC_TRAINER_ANIMAL", 'name': "animal", 'desc': "Animal Magic"},
    110 : {'code':"SPEC_TRAINER_AEGIS", 'name': "aegis", 'desc': "the Aegis of the Deities"},
    111 : {'code':"SPEC_TRAINER_SHAMAN", 'name': "shaman", 'desc': "The Ways of the Shaman"},
    115 : {'code':"SPEC_TRAINER_MAGE", 'name': "mage", 'desc': "the arts of Magic"},
    116 : {'code':"SPEC_TRAINER_MONK", 'name': "monk", 'desc': "the ways of the Monk"},
    117 : {'code':"SPEC_TRAINER_CLERIC", 'name': "cleric", 'desc': "the Ways of the Cleric"},
    118 : {'code':"SPEC_TRAINER_THIEF", 'name': "thief", 'desc': "the Ways of the Thief"},
    119 : {'code':"SPEC_TRAINER_PLANTS", 'name': "plants", 'desc': "about Plants and Herbs"},
    120 : {'code':"SPEC_TRAINER_SOLDIERING", 'name': "soldiering", 'desc': "Soldiering Skills"},
    121 : {'code':"SPEC_TRAINER_BLACKSMITHING", 'name': "blacksmithing", 'desc': "Blacksmithing Skills"},
    122 : {'code':"SPEC_TRAINER_DEIKHAN_MARTIAL", 'name': "martial", 'desc': "Martial Abilites for Deikhans"},
    123 : {'code':"SPEC_TRAINER_MOUNTED", 'name': "mounted", 'desc': "about Mounted Abilities"},
    124 : {'code':"SPEC_TRAINER_DEIKHAN_GUARDIAN", 'name': "guardian", 'desc': "Guardian Abilites for Deikhans"},
    125 : {'code':"SPEC_TRAINER_DEIKHAN_ABSOLUTION", 'name': "absolution", 'desc': "Absolution Abilities for Deikhans"},
    126 : {'code':"SPEC_TRAINER_DEIKHAN_VENGEANCE", 'name': "vengeance", 'desc': "Vengeance for Deikhans"},
    127 : {'code':"SPEC_TRAINER_LEVERAGE", 'name': "leverage", 'desc': "about Balance and Leverage"},
    128 : {'code':"SPEC_TRAINER_MINDBODY", 'name': "mindbody", 'desc': "about Mind and Body Control"},
    131 : {'code':"SPEC_TRAINER_FOCUSED_ATTACKS", 'name': "focused", 'desc': "about Focused Attacks"},
    133 : {'code':"SPEC_TRAINER_BAREHAND", 'name': "barehand", 'desc': "about Barehand Specialization"},
    134 : {'code':"SPEC_TRAINER_THIEF_FIGHT", 'name': "fighting", 'desc': "Fighting Skills for Thieves"},
    135 : {'code':"SPEC_TRAINER_POISONS", 'name': "poisons", 'desc': "about Poisons"},
    136 : {'code':"SPEC_TRAINER_SHAMAN_FROG", 'name': "frog", 'desc': "about the Abilities of the Frog"},
    137 : {'code':"SPEC_TRAINER_SHAMAN_ALCHEMY", 'name': "alchemy", 'desc': "Alchemy Spells for Shamans"},
    138 : {'code':"SPEC_TRAINER_SHAMAN_SKUNK", 'name': "skunk", 'desc': "about the Abilities of the Skunk"},
    139 : {'code':"SPEC_TRAINER_SHAMAN_SPIDER", 'name': "spider", 'desc': "about the Abilities of the Spider"},
    140 : {'code':"SPEC_TRAINER_SHAMAN_CONTROL", 'name': "control", 'desc': "about Being Controling"},
    141 : {'code':"SPEC_TRAINER_RITUALISM", 'name': "ritualism", 'desc': "about Rituals"},
    144 : {'code':"SPEC_TRAINER_COMBAT", 'name': "combat", 'desc': "Combat Skills"},
    145 : {'code':"SPEC_TRAINER_STEALTH", 'name': "stealth", 'desc': "about Stealthiness"},
    146 : {'code':"SPEC_TRAINER_TRAPS", 'name': "traps", 'desc': "about Locks and Traps"},
    148 : {'code':"SPEC_TRAINER_LORE", 'name': "lore", 'desc': "about Magic Lores"},
    149 : {'code':"SPEC_TRAINER_THEOLOGY", 'name': "theology", 'desc': "about Theology"},
    159 : {'code':"SPEC_TRAINER_DEFENSE", 'name': "defense", 'desc': "about Defense"},
    162 : {'code':"SPEC_TRAINER_PSIONICS", 'name': "psionics", 'desc': "about psionics"},
    169 : {'code':"SPEC_TRAINER_IRON_BODY", 'name': "iron body", 'desc': "about iron body techniques"},
    196 : {'code':"SPEC_TRAINER_ADV_ADVENTURING", 'name': "advanced adventuring", 'desc': "about advanced adventuring"},
    220 : {'code':"SPEC_TRAINER_OFFENSE", 'name': "offense", 'desc': "about Offense"},
    29 : {'code':"SPEC_GM_MAGE", 'name':"mage guildmaster", 'desc':"mage guildmaster"},
    30 : {'code':"SPEC_GM_DEIKHAN", 'name':"deikhan guildmaster", 'desc':"deikhan guildmaster"},
    31 : {'code':"SPEC_GM_MONK", 'name':"monk guildmaster", 'desc':"monk guildmaster"},
    32 : {'code':"SPEC_GM_WARRIOR", 'name':"warrior guildmaster", 'desc':"warrior guildmaster"},
    33 : {'code':"SPEC_GM_THIEF", 'name':"thief guildmaster", 'desc':"thief guildmaster"},
    34 : {'code':"SPEC_GM_CLERIC", 'name':"cleric guildmaster", 'desc':"cleric guildmaster"},
    35 : {'code':"SPEC_GM_RANGER", 'name':"ranger guildmaster", 'desc':"ranger guildmaster"},
    143 : {'code':"SPEC_GM_SHAMAN", 'name':"shaman guildmaster", 'desc':"shaman guildmaster"}
    }